name: Python CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup python for tox
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.13
      - name: install tox
        run: python -m pip install tox
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.1.0
        with:
          miniconda-version: "latest"
          python-version: 3.13
      - uses: actions/checkout@v4.2.2
      - name: Run tox
        run: tox
